name: example_playground
description: "An example Flutter project to demonstrate mvvm_kit usage."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  objectbox: ^5.0.2
  mvvm_kit:
    path: ../
  objectbox_flutter_libs: ^5.0.2 
  provider: ^6.1.5+1
  get_it: ^9.0.5

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.10.2 
  objectbox_generator: ^5.0.2 

flutter:
  uses-material-design: true

objectbox:
  output_dir: data/database
