name: example_playground
description: "An example Flutter project to demonstrate mvvm_kit usage."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0
  objectbox: ^5.0.2
  mvvm_kit:
    path: ../package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
